name: Slither Analysis
on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  SAST_Scanning:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
          version: nightly

    - name: Display config
      run: forge config

    - name: Compile contracts
      run: make artifacts  

    - name: Run Slither
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true 
      with:
        sarif: results.sarif
        exclude_low: false

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: sast_slither_output 
          path: results.sarif #commentsss
